---
version: "3"

services:

  # --- MariaDB
  db:
    container_name: "linkace-db"
    image: mariadb:10.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - linkace-db:/bitnami

  # --- PHP
  php:
    container_name: "linkace-php"
    build:
      context: .
      dockerfile: ./resources/docker/dockerfiles/development.Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:delegated
      - ./resources/docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php.ini:ro

  # --- nginx
  nginx:
    container_name: "linkace-nginx"
    image: bitnami/nginx:1.19
    ports:
      - "80:8080"
    depends_on:
      - php
    volumes:
      - .:/app:delegated
      - ./resources/docker/nginx/dev.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro

  # --- Redis
  redis:
    container_name: "linkace-redis"
    image: bitnami/redis:6.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  linkace-db:
    driver: local
